#app:
#  domain: https://gazi-s-dev.kildare.co.kr

springdoc:
  swagger-ui:
    enabled: true #release환경에서는 swagger-ui.html 노출이 가능

#release 환경 db 커넥션 정보
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/gazi?useUnicode=yes&characterEncoding=utf-8&serverTimezone=Asia/Seoul
#    username: root
#    password: Bizkil@0404

jwt:
  issuer: miribojob-release
  secret: ${JWT_SECRET_KEY:a2lsZGFyZVByb2plY3RHYXppSnd0U2VjcmV0UmVsZWFzZQ==} # 32자 이상의 키값 필요
  expire:
    minute : ${ACCESSTOKEN_EXPIRE_MINUTE:60}
    day : ${REFRESHTOKEN_EXPIRE_DAY:7}