#app:
#  domain: https://gazi-s.kildare.co.kr

springdoc:
  swagger-ui:
    enabled: false #prod환경에서는 swagger-ui.html 노출 불가

#prod 환경 db 커넥션 정보
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/gazi?useUnicode=yes&characterEncoding=utf-8&serverTimezone=Asia/Seoul
#    username: root
#    password: Bizkil@0404

jwt:
  issuer: miribojob
  secret: ${JWT_SECRET_KEY} # 32자 이상의 키값 필요
  expire:
    minute : ${ACCESSTOKEN_EXPIRE_MINUTE:60}
    day : ${REFRESHTOKEN_EXPIRE_DAY:7}